from pathlib import Path
from datetime import datetime, timezone
import json

ROOT = Path(__file__).parent
RELEASES = ROOT / "releases"
RELEASES.mkdir(exist_ok=True)

VERSION = "v1.4.10"

SOURCE_FILES = [
    "ACTIVE_CORE.md",
    "core/ACTIVE_CORE_REFERENCE_v1_4_10.md",
    "core/RULE_MAP_PUBLIC_v1_4_10.json",
    "MEMORY_BORIS_EGO_v1_7.md",
    "docs/ru/QUICKSTART.md",
    "docs/ru/LOCAL_BORIS_CONSTRUCTION_GUIDE.md",
    "docs/ru/CAPABILITY_AND_LIMITATION_MATRIX.md",
    "docs/ru/RESPONSIBLE_USE.md",
]

def read_file(path: str) -> str:
    full_path = ROOT / path
    if not full_path.exists():
        return f"[MISSING FILE: {path}]"
    return full_path.read_text(encoding="utf-8")

def main():
    built_at = datetime.now(timezone.utc).isoformat()

    sections = []
    for path in SOURCE_FILES:
        sections.append(
            f"\n\n# ===== SOURCE: {path} =====\n\n{read_file(path)}"
        )

    core_text = f"""# BORIS PUBLIC CORE RELEASE

Version: {VERSION}
Built at: {built_at}

This file is generated by build_release.py.
It is intended for BORIS Public Dashboard MVP.

Included sources:
{chr(10).join(f"- {p}" for p in SOURCE_FILES)}

{''.join(sections)}
"""

    latest_md = RELEASES / "latest-core.md"
    latest_md.write_text(core_text, encoding="utf-8")

    latest_json = {
        "system": "BOIS/BORIS",
        "version": VERSION,
        "type": "dashboard_core_bundle",
        "status": "generated",
        "built_at": built_at,
        "active_core": "BOIS main v2.23",
        "sima": "v0.4",
        "ego": "v1.7",
        "source_files": SOURCE_FILES,
        "core_text_file": "releases/latest-core.md",
        "core_text": core_text,
    }

    (RELEASES / "latest.json").write_text(
        json.dumps(latest_json, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    print("Generated:")
    print(f"- {latest_md}")
    print(f"- {RELEASES / 'latest.json'}")

if __name__ == "__main__":
    main()
